/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PagarRouteImport } from './routes/pagar'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ApiPublicAbacatepayWebhookRouteImport } from './routes/api/public/abacatepay-webhook'
import { Route as ApiPublicCheckOrderStatusRouteImport } from './routes/api/public/check-order-status'
import { Route as ApiPublicCreatePaymentRouteImport } from './routes/api/public/create-payment'
import { Route as ApiPublicRenewalRetriesRouteImport } from './routes/api/public/renewal-retries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarRoute = PagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAbacatepayWebhookRoute =
  ApiPublicAbacatepayWebhookRouteImport.update({
    id: '/api/public/abacatepay-webhook',
    path: '/api/public/abacatepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCheckOrderStatusRoute =
  ApiPublicCheckOrderStatusRouteImport.update({
    id: '/api/public/check-order-status',
    path: '/api/public/check-order-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreatePaymentRoute = ApiPublicCreatePaymentRouteImport.update({
  id: '/api/public/create-payment',
  path: '/api/public/create-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenewalRetriesRoute = ApiPublicRenewalRetriesRouteImport.update({
  id: '/api/public/renewal-retries',
  path: '/api/public/renewal-retries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pagar': typeof PagarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/abacatepay-webhook': typeof ApiPublicAbacatepayWebhookRoute
  '/api/public/check-order-status': typeof ApiPublicCheckOrderStatusRoute
  '/api/public/create-payment': typeof ApiPublicCreatePaymentRoute
  '/api/public/renewal-retries': typeof ApiPublicRenewalRetriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pagar': typeof PagarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/abacatepay-webhook': typeof ApiPublicAbacatepayWebhookRoute
  '/api/public/check-order-status': typeof ApiPublicCheckOrderStatusRoute
  '/api/public/create-payment': typeof ApiPublicCreatePaymentRoute
  '/api/public/renewal-retries': typeof ApiPublicRenewalRetriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pagar': typeof PagarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/abacatepay-webhook': typeof ApiPublicAbacatepayWebhookRoute
  '/api/public/check-order-status': typeof ApiPublicCheckOrderStatusRoute
  '/api/public/create-payment': typeof ApiPublicCreatePaymentRoute
  '/api/public/renewal-retries': typeof ApiPublicRenewalRetriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pagar'
    | '/reset-password'
    | '/admin'
    | '/r/$slug'
    | '/api/public/abacatepay-webhook'
    | '/api/public/check-order-status'
    | '/api/public/create-payment'
    | '/api/public/renewal-retries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pagar'
    | '/reset-password'
    | '/admin'
    | '/r/$slug'
    | '/api/public/abacatepay-webhook'
    | '/api/public/check-order-status'
    | '/api/public/create-payment'
    | '/api/public/renewal-retries'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pagar'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/r/$slug'
    | '/api/public/abacatepay-webhook'
    | '/api/public/check-order-status'
    | '/api/public/create-payment'
    | '/api/public/renewal-retries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PagarRoute: typeof PagarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicAbacatepayWebhookRoute: typeof ApiPublicAbacatepayWebhookRoute
  ApiPublicCheckOrderStatusRoute: typeof ApiPublicCheckOrderStatusRoute
  ApiPublicCreatePaymentRoute: typeof ApiPublicCreatePaymentRoute
  ApiPublicRenewalRetriesRoute: typeof ApiPublicRenewalRetriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar': {
      id: '/pagar'
      path: '/pagar'
      fullPath: '/pagar'
      preLoaderRoute: typeof PagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/abacatepay-webhook': {
      id: '/api/public/abacatepay-webhook'
      path: '/api/public/abacatepay-webhook'
      fullPath: '/api/public/abacatepay-webhook'
      preLoaderRoute: typeof ApiPublicAbacatepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-order-status': {
      id: '/api/public/check-order-status'
      path: '/api/public/check-order-status'
      fullPath: '/api/public/check-order-status'
      preLoaderRoute: typeof ApiPublicCheckOrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-payment': {
      id: '/api/public/create-payment'
      path: '/api/public/create-payment'
      fullPath: '/api/public/create-payment'
      preLoaderRoute: typeof ApiPublicCreatePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/renewal-retries': {
      id: '/api/public/renewal-retries'
      path: '/api/public/renewal-retries'
      fullPath: '/api/public/renewal-retries'
      preLoaderRoute: typeof ApiPublicRenewalRetriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PagarRoute: PagarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicAbacatepayWebhookRoute: ApiPublicAbacatepayWebhookRoute,
  ApiPublicCheckOrderStatusRoute: ApiPublicCheckOrderStatusRoute,
  ApiPublicCreatePaymentRoute: ApiPublicCreatePaymentRoute,
  ApiPublicRenewalRetriesRoute: ApiPublicRenewalRetriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
